# Generated by Django 4.1.7 on 2023-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hash_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
