# Generated by Django 4.1.7 on 2023-08-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_user_email_hash_user_hash_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash_time',
        ),
    ]
