# Generated by Django 4.1.7 on 2024-11-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_user_email_hash_user_hash_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash_time',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
