# Generated by Django 4.1.7 on 2024-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='copies_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=155, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='borrowrequests',
            table='borrow_requests',
        ),
    ]
